version: "3"

services:
  cyber-chef:
    image: mpepping/cyberchef:latest
    container_name: cyber-chef
    restart: unless-stopped
    ports:
      - '${APP_PORT}:8000'
    networks:
      - tipi_main_network

    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.cyber-chef-web-redirect.redirectscheme.scheme: https
      traefik.http.services.cyber-chef.loadbalancer.server.port: 8000
      # Web
      traefik.http.routers.cyber-chef-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.cyber-chef-insecure.entrypoints: web
      traefik.http.routers.cyber-chef-insecure.service: cyber-chef
      traefik.http.routers.cyber-chef-insecure.middlewares: cyber-chef-web-redirect
      # Websecure
      traefik.http.routers.cyber-chef.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.cyber-chef.entrypoints: websecure
      traefik.http.routers.cyber-chef.service: cyber-chef
      traefik.http.routers.cyber-chef.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.cyber-chef-local-insecure.rule: Host(`cyber-chef.${LOCAL_DOMAIN}`)
      traefik.http.routers.cyber-chef-local-insecure.entrypoints: web
      traefik.http.routers.cyber-chef-local-insecure.service: cyber-chef
      traefik.http.routers.cyber-chef-local-insecure.middlewares: cyber-chef-web-redirect
      # Local domain secure
      traefik.http.routers.cyber-chef-local.rule: Host(`cyber-chef.${LOCAL_DOMAIN}`)
      traefik.http.routers.cyber-chef-local.entrypoints: websecure
      traefik.http.routers.cyber-chef-local.service: cyber-chef
      traefik.http.routers.cyber-chef-local.tls: true
