version: "3.7"
services:
  aichat:
    container_name: aichat
    image: ghcr.io/cori/aichat:v0.20.0
    command: ["--serve", "0.0.0.0"]
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8000
    environment:
      AICHAT_CONFIG_DIR: /config
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
    volumes:
      - ${APP_DATA_DIR}/data:/config
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.aichat-web-redirect.redirectscheme.scheme: https
      traefik.http.services.aichat.loadbalancer.server.port: 8000
      # Web
      traefik.http.routers.aichat-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.aichat-insecure.entrypoints: web
      traefik.http.routers.aichat-insecure.service: aichat
      traefik.http.routers.aichat-insecure.middlewares: aichat-web-redirect
      # Websecure
      traefik.http.routers.aichat.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.aichat.entrypoints: websecure
      traefik.http.routers.aichat.service: aichat
      traefik.http.routers.aichat.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.aichat-local-insecure.rule: Host(`aichat.${LOCAL_DOMAIN}`)
      traefik.http.routers.aichat-local-insecure.entrypoints: web
      traefik.http.routers.aichat-local-insecure.service: aichat
      traefik.http.routers.aichat-local-insecure.middlewares: aichat-web-redirect
      # Local domain secure
      traefik.http.routers.aichat-local.rule: Host(`aichat.${LOCAL_DOMAIN}`)
      traefik.http.routers.aichat-local.entrypoints: websecure
      traefik.http.routers.aichat-local.service: aichat
      traefik.http.routers.aichat-local.tls: true
      runtipi.managed: true
