version: '3.5'
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    hostname: 0.0.0.0
    ports:
      - "33001:3001"
    cap_add:
      - SYS_ADMIN
    volumes:
      - "/home/cori/anythingllm:/app/server/storage"
      - "/home/cori/anythingllm/.env:/app/server/.env"
    environment:
      - STORAGE_DIR=/app/server/storage
